### ISSUE TITLE
Pre-built version request

### ISSUE THREAD

**Issue by nguoihocnghe** [JamesKyburz/svg-sketch-pdf#39]
Can you please provide the compiled js file of this library so that we can use it in non-NodeJS projects?

**Comment by JamesKyburz** [comment]
Added [minified version](https://github.com/JamesKyburz/svg-sketch-pdf/blob/master/svg-sketch-pdf.min.js).

`window.SvgSketchPdf` will then be exposed.

The file is large because it includes all the embedded [pdfkit[(https://www.npmjs.com/package/pdfkit) fonts.
